### ISSUE TITLE
Canceling map bug

### ISSUE THREAD

**Issue by OfficerHonk** [Foohy/jazztronauts#1]
When you decide against a map and call the bus back, you are unable to call the bus for a different map, as if the button is completely unusable.

**Comment by Foohy** [comment]
The absolute latest version just updated the map to address this, does it still happen all the time for you?
It's not a perfect fix yet, but it does make it harder for it to happen.

(If you haven't yet, restart gmod and you'll get the latest update)

**Comment by Foohy** [comment]
Should be fixed. Reopen if it still happens.

**Comment by Rasl808** [comment]
I have the same problem right now, is there a way to fix it?

**Comment by Foohy** [comment]
Should be fixed, the host behind jazz.foohy.net/addons.txt actually ran out of space and stopped having a valid addon list the last time it updated, woops.

**Comment by Rasl808** [comment]
Thanks!

вт, 5 нояб. 2024 г., 11:52 Scott Kauker ***@***.***>:
