### ISSUE TITLE
Upgrade screen Isn't working.

### ISSUE THREAD

**Issue by Jesseroo** [Foohy/jazztronauts#100]
When I go to the upgrade screen I only ever see the top of the first upgrade and cannot click on anything essentially barring me from upgrading 
![Capture](https://user-images.githubusercontent.com/62563956/89113344-573a1180-d435-11ea-9a4b-705895398ddb.PNG)

**Comment by leonbeer** [comment]
same thing here, just with i can only buy the first two upgrades

**Comment by Foohy** [comment]
This issue is 2 years old and there's been some pretty significant changes to the systems here, so I'm going to close it for now. But if it's still an issue please reopen it!
