### ISSUE TITLE
Areaportals do not open when linked doors are snatched

### ISSUE THREAD

**Issue by Zman6258** [Foohy/jazztronauts#104]
Title. When snatching a prop_door that has a func_areaportal linked to it, the associated areaportal isn't opened, thus causing a "void" where culled geometry is visible. I can think of two ways around this; either looking for the name of an areaportal specified in the door's properties, or just by firing the "open" input on the door a split second before it's snatched. I'd personally recommend the latter, as then you'd also fire any inputs tied to that doors OnOpen output, which might help reduce instances of maps breaking.

**Comment by skauker-iw** [comment]
This is a good idea, I'm sure a lot of maps break due to the prop snatcher just deleting the door without opening it.

**Comment by Foohy** [comment]
This is a good idea, I'm sure a lot of maps break due to the prop snatcher just deleting the door without opening it.

**Comment by Foohy** [comment]
Fixed in a35bb63bccafcd5d27be148704ba1077658131d4
