### ISSUE TITLE
Events out of order

### ISSUE THREAD

**Issue by FatesTimelines1337** [Foohy/jazztronauts#110]
When replaying previously seen events for each cat, the events do not play from event 0 to event 5 and instead play each event out of order. I assume this has something to do with how quest progress for each cat is saved through new game plus cycles.

**Comment by FatesTimelines1337** [comment]
Ok, I reset my mission progress using _jazz_missions_reset_all_. I redid the missions then started a new game plus cycle, it did not fix the order of the events and they appear to be playing in this order:

- Pianist: 1, 2, 3, 5, 4, 0
- Cellist: 3, 5, 4, 0, 2, 1
- Singer: 5, 3, 2, 1, 4, 0
- Bartender: 3, 1, 5, 0, 4, 2

**Comment by Commenter25** [comment]
This has been resolved, and should be closed.

**Comment by Foohy** [comment]
Should be fixed in #120.
