### ISSUE TITLE
Broken map transition.

### ISSUE THREAD

**Issue by sUmbra1** [Foohy/jazztronauts#111]
Game crashes after you select a map and ride the train, when the transition starts you get back to the main menu.

**Comment by Foohy** [comment]
This is "fixed" in the dev branch of Garry's Mod, see this discussion for why it was happening: https://github.com/Facepunch/garrysmod-issues/issues/4977. I don't know the timeframe of when this'll be merged into the shipping version of GMod though.

As of the latest update, running on the non-dev version of gmod will fallback to only loading locally-installed maps and addons instead.
