### ISSUE TITLE
Use Jazztronaut tools in Sandbox singleplayer

### ISSUE THREAD

**Issue by NekoAlosama** [Foohy/jazztronauts#117]
I think it would be nice to use items like the Stan and the I/O viewer on their own, preferably fully upgraded or have toggles. I haven't researched much on how to find functional alternatives to these, or be able to extract them from the mod and mount them as separate addons.

**Comment by Fighterbuilder** [comment]
Agreed! The I/O Viewer in particular would be really nice to have outside of Jazztronauts.

**Comment by ZakBlystone** [comment]
We're working on a standalone I/O Viewer now. :)

**Comment by NekoAlosama** [comment]
@ZakBlystone 

> We're working on a standalone I/O Viewer now. :)

How much progress has been made?

**Comment by ZakBlystone** [comment]
@NekoAlosama a lot of progress has been made on the I/O viewer, but I've been bouncing between several side projects and it's still got some bugs to iron out.

However it does a lot more than simply viewing the I/O now  >:)
[Here's a little peek](https://www.youtube.com/watch?v=_VtSDBs0y5c)

For anyone who would like to try it out send me a DM on Discord (Zak#1111 [case-sensitive]) and I can hook you up with the addon for testing.

**Comment by tntguy12355** [comment]
i'm a little late but [here the link](https://steamcommunity.com/sharedfiles/filedetails/?id=2992345126) @NekoAlosama

**Comment by NekoAlosama** [comment]
eh fine, gonna close this. i don't think the sweps are gonna get updated except for compatibility. i'm still interested in @ZakBlystone['s version](https://github.com/ZakBlystone/gmod_worldtools), but they've been coding other projects for 2 years now
