### ISSUE TITLE
Leaderboard text broken in Linux

### ISSUE THREAD

**Issue by TheShinyCookie** [Foohy/jazztronauts#118]
When playing on the Linux client, the text on the leaderboard is broken, and uses random Unicode characters. I understand that Linux builds of Source engine games have different fonts, but would there be a way to work around this?

![image](https://user-images.githubusercontent.com/42484937/130369620-763ce29e-1e93-4427-9566-791abbb89830.png)

**Comment by Rollecoster0** [comment]
installing Impact font should fix this issue

**Comment by Commenter25** [comment]
There may be a way to distribute Impact with Jazztronauts, or at least add some sort of notice to have it installed, or maybe add a fallback font. But this is not a Linux specific issue, this is a "the user does not have impact installed" issue, which can happen with other fonts.

**Comment by Foohy** [comment]
I think a solution would be to just used a different font that we know exists, those boards are pretty thrown together anyways and impact isn't important to their styling.
