### ISSUE TITLE
weird lua bug making game run at 1 fps on tf2 map

### ISSUE THREAD

**Issue by scarletshadowzz** [Foohy/jazztronauts#132]
[Jazztronauts] gamemodes/jazztronauts/gamemode/map/mapgen.lua:405: attempt to call field 'GetCurrent' (a nil value)
  1. CalculateShardCount - gamemodes/jazztronauts/gamemode/map/mapgen.lua:405
   2. GenerateJazzEntities - gamemodes/jazztronauts/gamemode/init.lua:185
    3. Run - gamemodes/jazztronauts/gamemode/init.lua:153
     4. StartMap - gamemodes/jazztronauts/gamemode/playerwait/playerwait.lua:129
      5. v - gamemodes/jazztronauts/gamemode/playerwait/playerwait.lua:163
       6. unknown - lua/includes/modules/hook.lua:96

this weird lua error keeps showing up every time i load a tf2 map, any idea why? the map i loaded in particular was ctf_2fort... idk why it lags so bad

**Comment by ZakBlystone** [comment]
Yep, this is a bug with TF2 maps. The data in the .bsp file is compressed and the loader cannot parse it.
We have an experimental branch we're working on to solve this problem.

**Comment by thekirbykid20067** [comment]
i hope this gets fixed soon, i own almost every game that can be mounted to gmod and i think it'd be cool to just play with those, especially if i'm offline

**Comment by Commenter25** [comment]
The bsp3 branch has now been merged, and I was able to play cp_dustbowl just fine; so I think this can be closed, possibly along with a few other issues related to Valve maps.

**Comment by Foohy** [comment]
Yep TF2 maps should be working fine with that branch being merged in. Closing this one!
