### ISSUE TITLE
don't allow the player to leave the chair when they're in the bus and the bus is traveling 

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [Foohy/jazztronauts#15]

**Comment by Foohy** [comment]
I think it's kinda funny if they get pummeled by a moving bus, but yeah if they're already in the void for the map exit bus they're just sorta sitting there.

**Comment by no-boot-device** [comment]
the issue is that they *don't* get pummeled by a moving bus if they're leaving a map, they just go out and back into the map as if nothing ever happened
