### ISSUE TITLE
Maps updated since 2020 fail to download

### ISSUE THREAD

**Issue by Commenter25** [Foohy/jazztronauts#176]
Testing on Linux through Proton, on both stable and x64 Gmod, and it happens regardless of selecting Peer-To-Peer or Local Server. The cutoff point is mid-January 2020, coinciding with the [January 2020 changes to the Workshop](https://gmod.facepunch.com/news/january-2020-update). Anything before downloads fine, anything after won't.
  
:heavy_check_mark: Downloads fine:
`1948157529` - 2019-12
`1956033416` - 2020-01-01
`1959773512` - 2020-01-05
`1963752858` - 2020-01-08

❌ Doesn't work:
`1973925394` - 2020-01-19
`1978946031` - 2020-01-25
`1983364258` - 2020-02
`1961027163` - 2020-01-05, updated 2020-11
`1932491380` - 2019-12, updated 2021-03
`1627575684` - 2019-01, updated 2022-09
`2984088899` - 2023-06

All the screens say "Failed to download from workshop", and the console prints the following:
```
DownloadGMA_Dedicated FAILED: 	Specified addon uses the new UGC workshop system, which is not compatible
Using fallback, DownloadGMA_Listen
Download workshop addon 2984088899 on client via DownloadUGC
steamworks.DownloadUGC: Failed to download addon 2984088899, Insufficient privilege
Finished steamworks.DownloadUGC - 	nil
Client finished with download file: 
Failed to download addon: Failed to download from workshop
```

It seems this was first mentioned [in the Steam discussions](https://steamcommunity.com/workshop/filedetails/discussion/1452613192/3077621289888589079/), and supposed to be fixed by https://github.com/Foohy/jazztronauts/commit/69a781882362c3dfdd510cd829741933ffc69bbb, but it's still an issue. Some have commented on the workshop with this same issue:  
![Hirjo says "specified addon uses the new ugc workshop system"](https://github.com/Foohy/jazztronauts/assets/35016761/1ce06814-b812-4683-afa6-e5414f2317d4)
![Bubbadoo says "I do wish that this had some way to filter the random maps on the tv level select to be just the ones that work. It seems like half of my time selecting maps is being bummed out because of a fail to download due to UGC"](https://github.com/Foohy/jazztronauts/assets/35016761/80c7cfc1-f42c-4d74-8c33-3097488339e2)

**Comment by Commenter25** [comment]
False report, was an issue with my personal setup.

**Comment by Jcdiem** [comment]
There is a library as a stop-gap for until they (never) implement this serverside.
https://github.com/WilliamVenner/gmsv_workshop
Would it be possible to have this fix added to the github or Steam Workshop page description? As it is the only way I've found for dedicated server users to have a working non-limited Jazztronauts experience.
