### ISSUE TITLE
Cats wont acknowledge props/mission progress

### ISSUE THREAD

**Issue by benjaminpants** [Foohy/jazztronauts#185]
Cleared my save data and started playing on the latest version(on the main branch), however, I'm unable to progress, as none of the cats acknowledge my props.

![image](https://github.com/Foohy/jazztronauts/assets/27522994/a6e637d6-7d2a-4b08-b437-0c619d9fa7c9)

(Bartender giving me the "having trouble finding crates" message despite me having enough crates)
![image](https://github.com/Foohy/jazztronauts/assets/27522994/67b0dcaa-2427-4b99-b831-97e25174c27d)

**Comment by Commenter25** [comment]
I attempted to replicate this myself, both with cheats and naturally, with the same amount of props, with no luck. Would you be willing to try running the cheat `jazz_missions_add 1` and see if you're suddenly able to progress?

**Comment by benjaminpants** [comment]
Nope, doesn't work. I've tried calling the refresh console commands and despite my best efforts it won't let me progress. I've already tried restarting the file from scratch before creating this issue and this issue persists. I have no clue why this is happening to me specifically, as I have all other addons disabled. (Excluding some local ones, which as far as I know should not be interfering, since I made all of them.)

![image](https://github.com/Foohy/jazztronauts/assets/27522994/4c72b614-4daa-4298-9644-539adcbb331d)

**Comment by benjaminpants** [comment]
Removed all my local addons to be sure, still not working.

**Comment by benjaminpants** [comment]
Looks like I have a duplicate instance of Jazztronauts installed somewhere, as I deleted my local copy and I'm currently unsubscribed from the workshop copy, so this looks like a problem on my end, thanks for responding quickly though!

**Comment by benjaminpants** [comment]
Re-opening issue, as after clearing the extra copy it still doesn't work. The version on the workshop, does work properly however, so this is a bug with the version on the repo.

**Comment by Commenter25** [comment]
Gotcha, if you find out anything more just mention it, I'll try again in the morning, maybe I messed something up myself.

Just want to say thank you for giving such thorough details! It's greatly appreciated and makes things far easier :D

**Comment by benjaminpants** [comment]
When I was in the workshop version, I completed Singer's mission. I switched back to the github version of the repo without completing the cutscene, and it appears like the cutscene and the next mission request worked. Seems like specifically completing a mission is broken?
![image](https://github.com/Foohy/jazztronauts/assets/27522994/31dcbb6d-9b3e-4d01-8436-b38d48c8419b)

**Comment by Commenter25** [comment]
I'm sorry, I keep trying, but I really can't replicate this; even after unsubscribing from the workshop addon and clearing the workshop cache from `steamapps/workshop/content/4000/1452613192`, and even completely decoupling the addon from the workshop by removing the ID from `gamemodes/jazztronauts/jazztronauts.txt`. All things which should eliminate possibility of duplicate installs overriding anything. I can't think of anything else to try.

I doubt it's relevant, but what operating system are you running, and which branch of Gmod are you on? Can you try the things I mentioned above and see if something miraculously changes?

**Comment by benjaminpants** [comment]
Windows 10 Pro 21H2, and I'm on the standard branch of Garry's Mod. Both of the things you suggested hasn't fixed the problem for me. In a few hours when I have the time I'm going to try to manually download every commit inbetween the workshop version to the latest commit, and see which one causes it to break. I appreciate your patience and I hope we can figure this out.

**Comment by benjaminpants** [comment]
Weird, looks like the issue fixed itself... strange. If it occurs again and I can track down which commit is causing it I'll re-open this issue but I appreciate the time you spent trying to help.
