### ISSUE TITLE
Stealing brushes underwater

### ISSUE THREAD

**Issue by lazyRares** [Foohy/jazztronauts#198]
Currently, stealing brushes underwater isn't possible. Since being inside a water brush counts as any other regular old brush, so the game prohibits you from taking the brushes that water obscures. This is problematic.

I'm not sure if there is any possible way to fix this since water is still a brush. Just leaving it here as an issue to get people thinking of a workaround, maybe a group steal upgrade? Something like that

**Comment by TheBillinator3000** [comment]
I also have the same issue. I usually type "sv_cheats 1" and "jazz_override_noclip 0" to steal all of the brushes. With these commands active, noclip into the brush you want to steal and boom! You got it.

**Comment by lazyRares** [comment]
Yep, this is how I've been doing it as well haha. But a proper method never hurts

**Comment by SageJFox** [comment]
Can confirm this. My guess would be needing to filter out water brushes from the snatcher's trace once they've been snatched. (*How* to go about doing that in a reasonable way is another issue. :P )

**Comment by SageJFox** [comment]
Fixed in d358da4ac124de239cf7f92b140f143968815cf8
