### ISSUE TITLE
Unable to play with friends

### ISSUE THREAD

**Issue by ZarenGaming72** [Foohy/jazztronauts#2]
So, whenever me and my friend/friends try to play the game together, whenever we reach the bar they always get kicked out of the game with the same message. Your map [maps/jazz_bar.bsp] differs from the server's. We tried this as of yesterday, so if there is a fix for it already, then my apologies.

**Comment by Kathy-Jones** [comment]
I am not one of the programmers, but I experienced this myself during testing: double check that you're subscribed to each part of the addon, and reinstall them all. If doing so via the workshop doesn't work, what did for me was downloading manually off GIT and following the instructions to install it in the gamemodes folder. I hope that helps!

**Comment by ZarenGaming72** [comment]
> Thanks! Completely forgot to close the discussion, I figured out that the workshop version was just buggy. But thank you eitherway for the help!
