### ISSUE TITLE
add config to allow adding sweps to store

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [Foohy/jazztronauts#20]

**Comment by Foohy** [comment]
Although not a config option, you can run lua to do it for you:
`jstore.Register(SWEP, price, options)` where options can include
desc = "description"
cat = "tools" or "upgrades"

**Comment by Commenter25** [comment]
Should this be closed, considering this functionality is already available?

**Comment by Foohy** [comment]
Yep, thirdparty.lua documents how to add new things to the store, and we have a documentation page here: 
https://github.com/Foohy/jazztronauts/wiki/Custom-Store-Items
Closing this one out as done!
