### ISSUE TITLE
Portable bus stop small glitch

### ISSUE THREAD

**Issue by AwertaDreams** [Foohy/jazztronauts#201]
You can leave the portable bus when its driving away from the current map.
Steps to reproduce:
1. Go to the portable bus, press e on the seat
2. wait about 2-3 seconds
3. Press e again to leave the seat
4. You're placed somewhere in the map.

**Comment by Commenter25** [comment]
Already fixed, just hasn't been pushed to the workshop.

**Comment by AwertaDreams** [comment]
> Already fixed in #169, just hasn't been pushed to the workshop.

Such a fast response! That's cool. Thanks ^^
