### ISSUE TITLE
find a way to disable kill triggers found in the spawnrooms of most dr_ maps

### ISSUE THREAD

**Issue by aus2004** [Foohy/jazztronauts#204]
There is usually a timed event in every dr_ map when the game starts that makes the spawn room instantly kill any player that walks into it or spawns in it, this can softlock the player as they are unable to even get the trolley to spawn if they die beforehand.

I'm not even sure if this is possible given the limitations of the source engine, but it would be nice if there was a way that the gamemode could detect that there is a kill barrier overlapping a spawnpoint within a certain distance and just permanently disable it.

**Comment by SageJFox** [comment]
Fixed in a399d8a2916b2c56602522285a3568e5c534ad31
