### ISSUE TITLE
Reference gmsv_workshop for Dedicated Servers on Jazztronauts

### ISSUE THREAD

**Issue by Jcdiem** [Foohy/jazztronauts#205]
In base Gmod the [steamworks.DownloadUGC](https://wiki.facepunch.com/gmod/steamworks.DownloadUGC) function is not available serverside, causing issues for dedicated server use of Jazztronauts.

There has been a module created, [/gmsv_workshop](https://github.com/WilliamVenner/gmsv_workshop), that loads as a DLL. This provides dedicated servers with the ability to use the new workshop system with all maps.
Would it be possible to have it mentioned as a "unsupported fix" on the workshop or GitHub?

**Comment by Commenter25** [comment]
I would do it myself, but I don't have permissions for it. The descriptions are all quite out of date in general, and the people who currently have permissions for everything are very busy. But it's one of the things on our to-do list, and I'll make sure that gets put in, so thank you for bringing it up!

**Comment by Foohy** [comment]
I've just updated the Workshop description to have a FAQ entry/category about dedicated server support that includes a direct link to gmsv_workshop, good call :)
https://steamcommunity.com/sharedfiles/filedetails/?id=1452613192
