### ISSUE TITLE
[Request] Add a way to reset snatched props

### ISSUE THREAD

**Issue by bubbyboytoo** [Foohy/jazztronauts#207]
When you have a lot of props collected, opening the spawn menu for the first time in a map can cause multi-second freezes as it tries to load everything at once. Having a command or something to reset that whole thing would be very useful, especially if you've unlocked the sandbox spawnmenu and basically made the base jazz prop-spawning obsolete anyway.

**Comment by SageJFox** [comment]
Seeing as Commenter's commit was thrown into my branch, gonna close this here. Also note that we've swapped the tab order on dcbcf4bf9b50a2126b187eaaa7433a235485e410 so the much more easily loaded Jazz weapons tab is first, which also greatly helps with this issue.
