### ISSUE TITLE
Certain Props Causing Immense Lag (Notably on Workshop TF2 Maps?)

### ISSUE THREAD

**Issue by lazyRares** [Foohy/jazztronauts#209]
Certain props when stolen cause immense lag and slow the game to a crawl. This seems to primarily happen on Team Fortress 2 maps posted on the workshop, and seems to encompass custom props that are not part of TF2's base. 

On **mvm_teien** specifically, once I spawned. I stole the nearby bamboo and rock models present and that's when the errors began. 

![image](https://github.com/Foohy/jazztronauts/assets/33793448/7193cb25-294b-4108-a511-8c3b71bc0084)
![image](https://github.com/Foohy/jazztronauts/assets/33793448/3161c21f-5009-4acc-b74e-dbb96a382a51)

**Comment by SageJFox** [comment]
Can confirm this, definitely seems to be models packed into TF2 maps. We're hanging hard on trying to load them for the staticprop shell.

**Comment by SageJFox** [comment]
Got to poke at this a little bit more, it's related to the compression that post-2015 TF2 workshop maps go under.

Maps like Shark Bay and Bread Space will cause hitches of varying lengths depending on the custom packed model's complexity and/or file size. Some are annoying but ultimately workable, others are 20+ minute affairs (Had to give up on the model portions of the ship on Shark Bay after over an hour of hitches, some lasting over 80 seconds/frame).

All that said, running bspzip's -repack on these maps (changing nothing else about them, not unpacking the models or anything like that) all but completely removes the hitches. That prop that took at least an hour before? Done with one singular 0.07 second hitch, the rest being hitchless.

Not a solution but hopefully a solid lead for someone better with this end of things to get a look at this.

**Comment by SageJFox** [comment]
Oh shoot I never followed up properly on this. Long story short is we were essentially re-unpacking these files for every bit we were trying to process (so on every vertex, etc.). This has been corrected and merging either [fast-mdl-loader](https://github.com/Foohy/jazztronauts/tree/fast-mdl-loader) or [sceneroots](https://github.com/SageJFox/jazztronauts/tree/sceneroots) will fix it on main.
