### ISSUE TITLE
Using this mode without workshop

### ISSUE THREAD

**Issue by Filimonov207** [Foohy/jazztronauts#213]
Hello! Is it possible to somehow play this mode without workshop in a non-licensed version of Garry's mod? I would personally like my downloaded maps to be downloaded from the computer and not from the workshop, I will be very grateful if you help me! Best regards, Dmitry F.

**Comment by SageJFox** [comment]
I don't know about non-licensed copies of the game, but, you can include only local maps by putting this into the server's console:
`jazz_include_external 0;jazz_include_localaddon 1;jazz_include_localmap 1`

**Comment by Filimonov207** [comment]
> I don't know about non-licensed copies of the game, but, you can include only local maps by putting this into the server's console:
> 
> `jazz_include_external 0;jazz_include_localaddon 1;jazz_include_localmap 1`

** Unfortunately, these three commands did not work. He writes me an error: “Failed to get latest addons.txt list!”.**

**Comment by Filimonov207** [comment]
> I don't know about non-licensed copies of the game, but, you can include only local maps by putting this into the server's console:
> 
> `jazz_include_external 0;jazz_include_localaddon 1;jazz_include_localmap 1`

I do not know if there are other ways to get around this "Darkshop". It's just that when I want to select local maps downloaded on my computer, it tries to download other random maps that are from the Workshop through the "Darkshop" system.
