### ISSUE TITLE
Missing Props in poker cutscene.

### ISSUE THREAD

**Issue by lazyRares** [Foohy/jazztronauts#218]
If previewed in Hammer, the poker cutscene room contains these props.

![image](https://github.com/Foohy/jazztronauts/assets/33793448/4815084e-0081-40f1-baa2-9531fa7dc6ce)

However, these are marked as `prop_static` and do not compile into the map as their prop does not support this. You can get these props to show up back again if they are recompiled marked as `prop_dynamic_override`. Or if we want to be correct in our ways, you can recompile them with the static flag.

![image](https://github.com/Foohy/jazztronauts/assets/33793448/c481b7fa-3129-4178-a4c3-b859f104795c)

**Comment by SageJFox** [comment]
Already fixed in either #166 or somewhere in [sceneroots](https://github.com/SageJFox/jazztronauts/tree/sceneroots)
