### ISSUE TITLE
Remove trigger_weapon_strip out of maps

### ISSUE THREAD

**Issue by EntityinArray** [Foohy/jazztronauts#220]
Some mappers make use of trigger_weapon_strip in their maps for smartass reasons.
Can you use your lua magic to prevent mappers from stripping jazztronaut tools from me?
For example, we could remove trigger_weapon_strip on map load

**Comment by SageJFox** [comment]
Figure this would be handled in the same sorta pass as #204 would.

**Comment by SageJFox** [comment]
Fixed in a399d8a2916b2c56602522285a3568e5c534ad31
