### ISSUE TITLE
Add Media Player to the bar

### ISSUE THREAD

**Issue by EntityinArray** [Foohy/jazztronauts#223]
Please, put the media player into the bar. Preferably there.

![image](https://github.com/Foohy/jazztronauts/assets/18554021/9c2e4dda-446e-4dfa-a5ba-adc351d525f3)

Just do ents.Create("mediaplayer_tv") and SetPos and its done

**Comment by SageJFox** [comment]
Handled... at some point on my branch, possibly here? 3fad193b45c04112917c9c24c23663bf4b92079c
