### ISSUE TITLE
Question about map brushes

### ISSUE THREAD

**Issue by mets11rap** [Foohy/jazztronauts#24]
If I'm not an idiot, map brushes are the things collected from right clicking, right? So, what's the point of them? I don't see myself collecting anything in the top left from doing it.

**Comment by pitaden** [comment]
it doesn't show the money you get from taking map brushes, but you do get money from it

**Comment by ZakBlystone** [comment]
I'm working on some changes to the prop-feed to show when you snatch props AND world brushes.

**Comment by Foohy** [comment]
Zak's changes are in! New event feed system to show brushes, props, shards, and player deaths.
Should be on the latest workshop build now

![](https://i.imgur.com/Js4PAsK.png)
