### ISSUE TITLE
Texture problems despite having all recommended games installed

### ISSUE THREAD

**Issue by fridtjof** [Foohy/jazztronauts#25]
I installed all of CS:S, HL2, EP1, EP2 and TF2 on my computer and added them in GMod.

Despite that, I'm still having visual bugs like this:

https://i.imgur.com/RAmhRmd.jpg
https://i.imgur.com/Y3m1iEf.jpg

I've checked the console for any obvious errors, but couldn't figure anything out.

It's getting spammed with these two error messages:

Setting void basetexture
GetSpriteAxes: Bad sprite type 1920300137

**Comment by fridtjof** [comment]
nvm, reinstalling the addon did the trick...

**Comment by Foohy** [comment]
Unfortunately this seems to be a common issue that's out of our control, but yes reinstalling the addon should hopefully fix it.
