### ISSUE TITLE
Dedicated server instant crash

### ISSUE THREAD

**Issue by OverwatchVoice** [Foohy/jazztronauts#3]
Almost immediately after a dedicated server finishes loading a map (Not jazz_bar), the server crashes.

**Comment by Foohy** [comment]
There's been a few updates addressing this, does it still happen? Also to rule out any incompatibilities, could you try with a fresh wipe + the official vanilla collection?
https://steamcommunity.com/workshop/filedetails/discussion/1452613192/1741090666216887580/

If that doesn't resolve it, could you attach a mdmp of the crash?

**Comment by OverwatchVoice** [comment]
Sorry, turns out the server was using outdated version of gmod and some LUA hooks were probably missing.
