### ISSUE TITLE
Needed rework for jazz_intro

### ISSUE THREAD

**Issue by mets11rap** [Foohy/jazztronauts#36]
Not to brag, but I have a pretty good PC, and even so, when I run the intro on singleplayer, the size of the map is too much to host for the server (since it's required) and to render for the client. I think it would take a load off if you made (if this isn't done already) sections of the map render/load for the client, rather than all at the same time. Also maybe unrender unneeded parts during cutscenes? I know this is a problem with map size specifically, because this doesn't happen on servers I'm not hosting.

**Comment by Zeni44** [comment]
After taking a quick peek at the map's .vmf (could be outdated however), there does seem to be little to no optimisation. 
However do read up on [visleafs](https://developer.valvesoftware.com/wiki/Visleaf), as they are basically what you are suggesting with the part section rendering of a map.
They are not perfect automated however and can be improved with skip/hint brushes in hammer etc.
