### ISSUE TITLE
nil value text bubbles.

### ISSUE THREAD

**Issue by OverwatchVoice** [Foohy/jazztronauts#44]
Whenever I try to initiate a dialogue in any way, the bubble is empty, with "nil" as the speaker.

Console prints out the following:
[ERROR] gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:311: attempt to call upvalue 'iter' (a nil value)
  1. nodeiter - gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:311
   2. nop - gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:109
    3. State - gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:190
     4. nop - gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:90
      5. Update - gamemodes/jazztronauts/gamemode/ui/dialog/cl_dialog.lua:299
       6. fn - gamemodes/jazztronauts/gamemode/ui/cl_init.lua:27
        7. unknown - lua/ulib/shared/hook.lua:109

EDIT: This can be fixed by downloading the content yourself instead through a dedicated server's workshop collections

**Comment by mets11rap** [comment]
So.... close the issue.....
