### ISSUE TITLE
Final "World Stealing Speed" upgrade can't be obtained due to overflow

### ISSUE THREAD

**Issue by Earthnuker** [Foohy/jazztronauts#46]
## Steps to reproduce
- `sv_cheats 1`
- clear NG+ infos (optional): `lua_run print(jsql.Query("DELETE FROM jazz_reset_info"));`
- or just clear everything: `jazz_reset_progress yep, dump it`
- reload map: `changemap jazz_bar`
- set current balance to 10,000,000,000 `lua_run print(jsql.Query("UPDATE jazz_player_money SET earned=10000000000,spent=0"))`
- set value of snatched props to effectively 0 and count to 1 `lua_run print(jsql.Query("UPDATE jazz_propdata SET total=0,recent=1,worth=0.0000000001"))`
- pull the lever at the prop drop chute to force a recalculation of your current balance

## Expected result:
- i have $10,000,000,000+a bit of change and can buy the upgrade
## Actual result
- i have $-(2^31)=$-2,147,483,648 and can't buy the upgrade

**Comment by Foohy** [comment]
I'll prolly just make it cheaper, since the gimmick is that it goes up by a factor of 10 every time.

**Comment by Commenter25** [comment]
This has been resolved, and should be closed.

**Comment by Foohy** [comment]
Yep, FWIW money has been converted to a 64bit integer so you can have insane prices, and I have since tweaked the algorithm to make each world stealing upgrade a much more significant boost over the previous.

Closing this as done
