### ISSUE TITLE
Improve Load Screen

### ISSUE THREAD

**Issue by Aubron** [Foohy/jazztronauts#47]
Just wondering, is there a desire to improve http://host.foohy.net/public/Documents/Jazz/ ?

Is its galaxy background and scrolling text its own joke? Would a nicely branded page there be destroying part of the charm?

If I make a PR for a better one, will it even matter? The source of the page on the web has analytics code on it, the one at https://github.com/Foohy/jazztronauts/blob/master/other/load/index.html does not.

So many questions.

**Comment by Foohy** [comment]
The 'lore' was that it was the singer's best effort in making a webpage to welcome all the new guests. (And also the singer recently got a google analytics account to which they still need to upload to gh-pages).

Right now there isn't any plans to make it better, but if people really think it detracts a lot, then maybe. Even without the lore I think it's got a bit of web 2.0 charm though.

**Comment by mets11rap** [comment]
Maybe add `©The Signer` somewhere?

**Comment by Aubron** [comment]
If I had an argument, which I don't think is _necessarily_ compelling, it would be that, assuming this individual is a first time jazztronaut, they don't know any lore at the time they're seeing this, including having no idea who the singer is, and instead get a first moment impression of the mod that I think under-represents its production value. If they did a bad job installing it, it could be the only thing they see before they decide if the mod is worth troubleshooting or passing on.

**Comment by mets11rap** [comment]
Maybe surround it with a border of the Singer's tablet so it looks like it's on the screen?

**Comment by mets11rap** [comment]
This should be closed.
