### ISSUE TITLE
Texture issue when summoning the bus

### ISSUE THREAD

**Issue by mets11rap** [Foohy/jazztronauts#48]
I assumed this issue was known and was going to be fixed, but after multiple updates, I can see it's not. With no graphical modifying addons, for some reason, in local 2 player mode, when I summon the bus the entire map becomes invisible and the only things I can see are the void, the bus, and the radio. This doesn't happen in servers I join; it only happens when I play the "singleplayer" mode AKA local 2 player.

(You're seeing a screenshot of a small map because I wanted to load in as quick as possible)

This is before the bus is summoned
![image](https://user-images.githubusercontent.com/20345400/43776373-a0fb931a-9a1d-11e8-9e16-44dee496b504.png)

And this is after
![image](https://user-images.githubusercontent.com/20345400/43776393-b7b075ee-9a1d-11e8-9358-9ceff5bbb070.png)
As you can see, the wall texture as disappeared. Although the static prop texture remains, regular props, even when not captured, do not.

Also, after looking in the console, I was able to determine this isn't an addon error because nothing out of the ordinary was logged.

**Comment by Foohy** [comment]
Hmm yeah I definitely haven't been experiencing that. Perhaps a video driver issue? The void effect + bus wall portal do some pretty strange things with stencils, and I wouldn't be surprised if some operation isn't doing what it should.

**Comment by mets11rap** [comment]
It couldn't be a video driver issue because this doesn't happen when I'm not hosting. I doubt it's any addons I have.
