### ISSUE TITLE
Inappropriate map in default whitelist

### ISSUE THREAD

**Issue by TinKelp** [Foohy/jazztronauts#49]
![20180807163233_1](https://user-images.githubusercontent.com/33504204/43801970-82af93bc-9a62-11e8-9d41-70a59df9200b.jpg)
Workshop ID is 485971602

Map causes a song to be played with a text-to-speech voice saying the n-word and a bunch of other offensive terms. And mentions violent things being done to them. A lot.

How the hell did this get on the list?

**Comment by Foohy** [comment]
Woops, yeah we don't actually go through all 16,000 maps, so unfortunately some awful ones will get through. I'll add it to a blacklist for the addon scanner, but in the mean time it can't hurt to report it to workshop directly as well. 
(removed/incompatible addons won't show up on the browser).
