### ISSUE TITLE
[could be spoiler] Seeing The Bartender Asserting Dominance through the snatched texture

### ISSUE THREAD

**Issue by Linkfan123** [Foohy/jazztronauts#50]
![Screenshot of me looking through a snatched world brush to see two copies of The Bartender T-Posing in the snatched brush](https://i.imgur.com/evWPmOE.jpg)

Donno if this is a story thing and I'm *supposed* to be like "wat" (since this game's fourth wall doesn't even exist), but if it is a bug, could you please fix it? It kinda goes a little more meta than the game already does, thus breaking immersion.

Thanks!  (￣▽￣*)ゞ

**Comment by dysmus** [comment]
![voidcat](https://user-images.githubusercontent.com/42190632/43808162-b660a2b6-9a79-11e8-9cb2-730cc7926c84.jpg)

**Comment by Linkfan123** [comment]
So the devs thought it was funny and thus it is a part of the lore.
Thank you Bartender, very cool!
