### ISSUE TITLE
jazz_apartments reflects missing texture (missing cubemaps?)

### ISSUE THREAD

**Issue by dysmus** [Foohy/jazztronauts#51]
![jazz](https://user-images.githubusercontent.com/42190632/43807768-fcc89d96-9a77-11e8-845b-9a0d94a8c07e.jpg)

not sure about the technical deets here. considering the context, I don't even know that this is unintentional :P

**Comment by mets11rap** [comment]
Do you have CSS activated?

**Comment by dysmus** [comment]
yes, all the standard gmod games are mounted

**Comment by Foohy** [comment]
Hi, did this ever go away? Sometimes cubemaps won't load correctly after being mounted/unmounted/whatever. Restarting usually fixes it though.

**Comment by mets11rap** [comment]
This issue should be closed.
