### ISSUE TITLE
Wrong dialogue when prompting about "that other cat"

### ISSUE THREAD

**Issue by dysmus** [Foohy/jazztronauts#54]
![jazzdia](https://user-images.githubusercontent.com/42190632/43903397-5a23e534-9bba-11e8-8e0a-162959c9a923.jpg)
When I choose the first option I get like two lines about "that  other cat" and then suddenly dialogue ostensibly from the "stuck in a rut" bit.
![jazzdia2](https://user-images.githubusercontent.com/42190632/43903406-5fde1b7a-9bba-11e8-84e3-8659bcae7e55.jpg)

**Comment by Commenter25** [comment]
This no longer happens, the issue should be closed.

**Comment by Foohy** [comment]
Yep there's been extensive dialog script changes since this, closing
