### ISSUE TITLE
[Spoilers, don't read if you haven't finished NG+] NG+ reset policy is kind of screwy-overy

### ISSUE THREAD

**Issue by 20kdc** [Foohy/jazztronauts#58]
Regarding the way the NG+ ending occurs, I get the feeling it's a little... screwy-overy?
Failing the NG+ ending checks will essentially remove the NG+ component from that run, though at least you don't have to refill the shard tank.
But for further NG+ access, you have to do another NG+ run. Including a reset to the start of NG+.
Including wiping any progress on the side missions, tools, going through the prologue again...

So the average player who doesn't know about the conditions is going to end up performing 3 runs, and that's assuming they guess that the 'third option' is the right one to press.
Run 1 is their actual first run. Depending on how completionist they are, they might do all the side missions on this run, but it won't help.
Run 2 is their NG+ run where they get screwed over by not having any information.
I'd daresay most people who did all side missions on Run 1 won't do them on Run 2, and most people who didn't really care about the side missions on Run 1 won't do them on Run 2.
Run 3 and onward are where they try to get it 'right'. People with sufficient technical knowledge will start backing up files at the start of Run 3 now they know the game's out to get them.

(Also, if a player happens to be curious about a given choice path, that's another run to add to the counter. Map loads aren't the fastest things in the world, and >20 of them nearly in a row isn't fun. During my Run 2, I tended to keep an ebook on hand.)

I don't particularly consider forced resets if you get specific impossible-to-know knowledge wrong 'difficulty', just 'hot-spice-grade skin irritant'. Essentially, the player spends a good amount of time retracing the exact same steps they've taken before, only with different furnishings.

It's not like the player can just revert to an older save unless they've been clued in on the fact you're storing the save data in `sv.db` (Was this *deliberately* chosen to be hard to untangle from unrelated data, or was it just for reliability reasons? It's definitely reliable, but the costs...)

Depending on their patience and technical capabilities, after they realize how Run 2 screwed them over they'll do one of the following:
1. Ragequit.
2. Grab sqlitebrowser and start learning how to skip past everything. With or without looking at the GitHub code.
3. Learn to be very careful about copying and backing up `sv.db`.
4. Wonder if any of this is even worth it.
5. Do all 4 of those things and then write a GitHub issue, knowing full well the player is going to get called salty, knowing said player probably deserves it, but just giving up on caring.

**Comment by HighGuard** [comment]
I have to agree on this. After doing the first run with all quests completed, I already didn't feel like doing them all again since they take quite a lot of time if you do them legitimately and I just couldn't make myself spend even more time on them. And when I realized that I actually have to complete them in order to get the good ending, I just gave up. I love the gamemode, I like the characters, but that's just too much.

**Comment by Kathy-Jones** [comment]
Thank you so much for the feedback! We're making adjustments accordingly.

**Comment by Foohy** [comment]
Yep, I 100% agree, its painfully punishing. We've talked about it, and we think what we're going to do, is just never reset mission progress in a ng+. Collecting all those props was a pain, is per-person, and it's admittedly really really hard to collect all those props in time before the ending begins.

This way we don't really have to change much code, a reset isn't quite as punishing, and everybody can collect props without fearing it'll just get reset in a few hours anyway.

Seem like a good compromise?

**Comment by 20kdc** [comment]
Hmm... given #62 this might be a matter of user preference. Given that, I'll close the issue.
Sorry about keeping this open so long, I... may have kind of forgot.
