### ISSUE TITLE
Cutscenes are buggy.

### ISSUE THREAD

**Issue by Toasty-Engineer** [Foohy/jazztronauts#6]
I think this is being addressed already but cutscenes have a lot of weird issues. Pictures included of examples. (Note: Yes, I'm on a 2 player server for singleplayer. That's not the issue.)
![20180801154247_1](https://user-images.githubusercontent.com/21232022/43548239-77f15926-95ab-11e8-8714-277cf17bfa91.jpg) I got so high the Cellist started speaking in Lua and the game threw a script error.
![20180801164413_1](https://user-images.githubusercontent.com/21232022/43548078-14ecb3de-95ab-11e8-96d7-8c2c62fdaad7.jpg) Text scrolls off the screen.
![20180801163954_1](https://user-images.githubusercontent.com/21232022/43548109-26890e08-95ab-11e8-8c5b-7b45f65b7e74.jpg) I'm floating, and Singer is still asleep from last cutscene.
![20180801164128_1](https://user-images.githubusercontent.com/21232022/43548158-49ed48b4-95ab-11e8-9bf8-72c503174dbb.jpg) Bartender has ceased to exist. Also, weird twisty legs.
![20180801154650_1](https://user-images.githubusercontent.com/21232022/43548199-62b23bde-95ab-11e8-920c-118255c5a669.jpg) Everyone but the Bartender is an ERROR and the Bartender is in a weird position.
![20180801144602_1](https://user-images.githubusercontent.com/21232022/43548315-9d26b3d0-95ab-11e8-8d60-541997b8d584.jpg) I'm awkwardly leaning forward.
(No screenshot for this one, might have been addressed already?) In the Cellist's first cutscene everyone is floating.
EDIT: Some script weirdness.
![20180801165659_1](https://user-images.githubusercontent.com/21232022/43548499-0920c5d0-95ac-11e8-9377-a9d5b12343e6.jpg) NUMBER terracotta pots.
![20180801165709_1](https://user-images.githubusercontent.com/21232022/43548515-15599b56-95ac-11e8-8bd9-f6dfdb40d593.jpg) Might be intentional, but "camera cut to show the flower pot".
(Sorry for posting 3 issues in a row, don't want to be spammy.)

**Comment by Toasty-Engineer** [comment]
![20180801173703_1](https://user-images.githubusercontent.com/21232022/43550439-8f63c9bc-95b1-11e8-824e-b33b9e786b51.jpg) The text for this cutscene doesn't even show.

**Comment by Toasty-Engineer** [comment]
I really love this gamemode but now it's kind of hard to play when cutscenes and dialogue are non-functional. Hope this gets fixed soon.

**Comment by Foohy** [comment]
The most recent few commits addressed this, could you try again to see if they're more stable now? Thanks!

**Comment by Toasty-Engineer** [comment]
Yeah, the cutscenes in question work now, thanks!
