### ISSUE TITLE
Shards can void-ify their own visual effects

### ISSUE THREAD

**Issue by commandhat** [Foohy/jazztronauts#61]
I grabbed a shard that appeared out on the road and suddenly my entire world started turning void. Obviously, this surprised me, so I ran backwards to figure out what was happening... until I noticed there were a bunch of cubes of random size appearing that all had the void material on it.

It did dissappear after generating about ~60 cubes, but it DID make a big mess in the road:

![2018-08-16_01-34-23](https://user-images.githubusercontent.com/3821018/44192421-f9e81100-a0f4-11e8-80fb-aed7648e597d.jpg)

**Comment by SquirrelKiev** [comment]
its to do with hidden world brushes, player clips, etc.

**Comment by SageJFox** [comment]
Workaround for this issue here 6bf58964e634daeb59eee1c191034dbd8ef05471
