### ISSUE TITLE
Missions wont reset

### ISSUE THREAD

**Issue by bjoern90** [Foohy/jazztronauts#62]
my mission wont reset after completing the game and doing the NQ+ https://i.imgur.com/cWuaaS9.png

**Comment by bjoern90** [comment]
also the game should be more harder when doing NQ+ like more shards or something

**Comment by Zeni44** [comment]
See:

Commit: [496434bada72ae528fc20f089221dfb2a52af521](https://github.com/Foohy/jazztronauts/commit/496434bada72ae528fc20f089221dfb2a52af521)

Issue: #58

**Comment by bjoern90** [comment]
eugh i hate this game now.
