### ISSUE TITLE
Impossible to get Max World Stealing, Negative Numbers impedes it.

### ISSUE THREAD

**Issue by SoraHjort** [Foohy/jazztronauts#66]
Due to how money is stored in the database file. As in, it's stored as a (4-byte) unsigned integer. It is impossible to get any money value above 2,147,483,647. Anything higher and it will roll into negative numbers. This is just how unsigned integers work. 

See video for demonstration on what happens when it tries to go above that value
 https://youtu.be/06RZtVHWEBw
(didn't trim the first five seconds of non-action)

I am unsure how Source handles databases, but the usual fix would to store it as BigInt or Int64. That would increase it from 2,147,483,647 to 9,223,372,036,854,775,807 before it rolled over. If possible for Jazztronauts, that would be a pretty impossible number to get to without cheating, or if you had a ton of highly active servers using the same database. Even then, that's pretty unlikely.

Now because of this limit, this means that after the $1,000,000,000 upgrade for World Stealing, it becomes impossible to get any more as it next jumps to $10,000,000,000.

So my suggestions for solutions

1. Change the Int type to allow for a larger positive value. With the larger it is highly unlikely that anyone will get to it within their life time. Though on the safe side, implement a cap to prevent a roll over into negatives.

2. Change the costs for the World Stealing upgrades to be more reasonable and within the current positive range limit. And then add in a cap at $2,000,000,000. That way it won't ever roll over into negatives, while making the upgrades possible.

**Comment by SoraHjort** [comment]
Something that I just realized, since I had gone looking through the database file. It stores both money earned and money spent. So the negative number issue might not be within the database file, but within the mod itself. Since it calculates the current money value with (Earned - Spent = Current).

**Comment by Foohy** [comment]
Hi I'm 2.5 years late, but actually internally the database stores those values as 64bit integers (the INT in gmod's sqlite version uses 8 byte representation), but none of the UI handled this correctly since it was being networked with a normal 32bit integer. 

Needless to say, fixed in 3bf43a9fcc6302454ee01416be0494db006b05d1
![image](https://user-images.githubusercontent.com/1835056/113399172-9cac3700-9354-11eb-926b-2311dfc72c1f.png)
