### ISSUE TITLE
Stan causes engine error

### ISSUE THREAD

**Issue by ghost** [Foohy/jazztronauts#67]
when i take out my the stan and aim at a wall the game crashes with the error:
`failed to lock vertex buffer in CMeshDX8::LockVertexBuffer: nVertexCount=4, nFirstVertex=2204`

From what i have seen, this seems to only happen on Linux.

**Comment by 20kdc** [comment]
The GMod Linux port is rather broken, so not Jazztronauts's fault. Wouldn't be surprised if the Mac OS X port is the same way.
Better to run it under Wine - the way the DX9 stuff is handled is a wrapper anyway, and if you have Gallium Nine then you're probably better off with Wine.
If doing that, be sure to play around in the graphics settings.
I have it set to multicore rendering on, windows aero extensions off, but adjust to what works.
-- a random person

**Comment by Commenter25** [comment]
Running Linux myself, I can confirm this is not an issue. And if it was, it would likely be an upstream Gmod problem. This should be closed.

**Comment by Foohy** [comment]
Yeah, unfortunately not something we would be able to fix ourselves unless we had a solid repro and a workaround. Closing for now.
