### ISSUE TITLE
TVs/Cats wont spawn

### ISSUE THREAD

**Issue by SenioremLuthicer** [Foohy/jazztronauts#70]
so i spawned in to the lobby walked forward and noticed the TV's were missing, thinking this was some scripted event i walked to the bar and noticed the cats were also gone. i did have other mods on and i'm going to attempt to get it working with these disabled.

**Comment by SenioremLuthicer** [comment]
Ok attempted without other mods did not work. help plz.

**Comment by the05animator** [comment]
> 
> 
> so i spawned in to the lobby walked forward and noticed the TV's were missing, thinking this was some scripted event i walked to the bar and noticed the cats were also gone. i did have other mods on and i'm going to attempt to get it working with these disabled.

there is a button at the bottom right corner of the screen saying "sandbox" click this and then click jazztronauts on the menu that appears and try again

**Comment by Foohy** [comment]
Closing this for now with no repro.
