### ISSUE TITLE
Jazz_Bar being treated as a normal map

### ISSUE THREAD

**Issue by Krayvern** [Foohy/jazztronauts#72]
https://imgur.com/a/V97Xotr
All the cats are spawning, crystals have spawned, and we have our normal tools like the portable buss and the prop snatcher.
This is on a dedicated server with no other mods. I've tried starting up a map and leaving it, using the bus in Jazz_Bar, and even restarting the intro.

**Comment by Foohy** [comment]
I think this can happen if you call `game.CleanUpMap()` at any point in the bar, which has been addressed in #120 I believe. Closing this out for now but please reopen if it's still occurring.
