### ISSUE TITLE
Global Malicous Map Blacklist

### ISSUE THREAD

**Issue by Cynosphere** [Foohy/jazztronauts#74]
Recently there was a [map uploaded](https://steamcommunity.com/sharedfiles/filedetails/?id=1276434642) to the workshop that has obfuscated DRM that kicks people off the server if the map is not running on the right server. Could there be a feature in the future to have a global blacklist of maps that are malicious like this to prevent being used in the gamemode?

**Comment by CommenterOfComments** [comment]
Well, the guy lives up to his username.
![username](https://user-images.githubusercontent.com/35016761/54053186-1d1b0080-41ac-11e9-9d48-1db67d2f5c19.png)

I doubt there are a lot of malicious maps like this, but a blacklist would probably be good to add to prevent this anyway. It could be used for other purposes, such as #75 that I just posted, or blocking "content packs" from appearing.

**Comment by Cynosphere** [comment]
>I doubt there are a lot of malicious maps like this
A month or two ago people were reuploading old maps saying they were "fixed" versions that had ad scripts in them so, yeah, its getting bad with backdoors and such on the workshop.

**Comment by Commenter25** [comment]
Coming back with hindsight, and knowledge of how the code works: while this 100% *could* be implemented, it would be a lot of maintenance work for an extremely small portion of the workshop, and I don't think it would be effective. Jazztronauts scrapes the latest addons on the workshop, and before any of us could learn something exists to blacklist, it would likely be reported and banned, or leave the pool Jazztronauts players would see.

As such, I feel like this should be closed. If you're worried about malicious maps, it'd be best to use an anti-backdoor addon such as [Backdoor Shield](https://steamcommunity.com/sharedfiles/filedetails/?id=2215013575).

**Comment by SageJFox** [comment]
Will agree with Commenter on this. In addition to what they said, such a list would either need to be made entirely manually or otherwise constantly moderated by us/volunteers to also prevent bad actors blacklisting perfectly fine maps. And ultimately it'd just be recreating the moderation of the workshop and hoping we're able to act before they do anyway.
