### ISSUE TITLE
No Dialogue or Tab Menu

### ISSUE THREAD

**Issue by AwsumN00b** [Foohy/jazztronauts#76]
When I try to play solo (in p2p mode of course) or host the gamemode, none of the dialogue appears on screen, game otherwise acts like the dialogue is there though i.e. I need to click through to exit it. As well as that the menu that appears when pressing tab isnt there.

Ive tried this with no other addons whatsoever as well as trying both the steam and gitbug versions. All of this works when someone else with a working client hosts the game.

I dont know what lines in the console are relevant that I might post here but I can present that if need be

**Comment by Foohy** [comment]
I think the systems at play here have been significantly changed since here, so I'm going to close this for now but please reopen if this is still happening!
