### ISSUE TITLE
Game crash in Singer cutscene

### ISSUE THREAD

**Issue by NekoAlosama** [Foohy/jazztronauts#77]
I'm at the Singer cutscene where they trip over a bunch of Hula dolls. My game crashes at the next text box

Tried without any other add-ons and still didn't work.

**Comment by Foohy** [comment]
Hmm, could you provide the .mdmp file generated from the crash? It should be in your root garrysmod/ directory. I can see if there's anything suspicious happening.

I'm assuming you're on windows, is that correct?

**Comment by NekoAlosama** [comment]
Nevermind
i was using the beta 64-bit version of gmod
switched back to the 32-bit vers and it was fixed
Here's the crash logs from the 64-bit vers anyways
[0118da1b-6ab8-448d-a112-96f225ae3202.txt](https://github.com/Foohy/jazztronauts/files/2994264/0118da1b-6ab8-448d-a112-96f225ae3202.txt)
