### ISSUE TITLE
floor is missing on jazz_bar and other issues pls respond

### ISSUE THREAD

**Issue by MaximeWTH** [Foohy/jazztronauts#79]
hi

i recently found jazztronauts and i thought that it was cool but when i got into the jazz bar i found out that the wall neer the bus stop was black and pink ant that the floor is missing
also the void af the stolen props is black and pink too
how do i fix

pls respond quick

**Comment by Foohy** [comment]
This was probably in the dark days when this gamemode was split across 3 separate addons, and was pretty easy to get in a situation where they weren't all mounted. I'm going to close this out as fixed since it's a single addon now. 
Please reopen if it still happens!
