### ISSUE TITLE
Can't complete Pianist's final quest.

### ISSUE THREAD

**Issue by Toasty-Engineer** [Foohy/jazztronauts#8]
Stolen Metro Police don't progress the meter whatsoever. It's the last quest I have :(
![20180802030812_1](https://user-images.githubusercontent.com/21232022/43568020-90a693f4-9601-11e8-9fd5-2476834fdd66.jpg)
![20180802030815_1](https://user-images.githubusercontent.com/21232022/43568029-9454879a-9601-11e8-9e0e-b78501d07d0f.jpg)

**Comment by no-boot-device** [comment]
What's the console command? Having the same issue.
