### ISSUE TITLE
Cutscenes does not check active VGUI element

### ISSUE THREAD

**Issue by DBotThePony** [Foohy/jazztronauts#87]
Pressing enter while cutscene is not focused (an other VGUI element is focused or player opened console) will still continue cutscene for player
![gmod_11-38-41-4cdda12](https://user-images.githubusercontent.com/6339511/71303108-c606b500-23e6-11ea-88ac-cb3abdf8b7fe.png)
https://wiki.garrysmod.com/page/vgui/GetKeyboardFocus

**Comment by Commenter25** [comment]
This has been resolved, and should be closed.

**Comment by Foohy** [comment]
Yep, this has been solved by #120
