### ISSUE TITLE
cl_snatch_kleiner does not check whenever entity is still valid

### ISSUE THREAD

**Issue by DBotThePony** [Foohy/jazztronauts#88]
Causing Lua error spam until kleiner complete "stealing" of entity which got removed in progress
![gmod_11-19-57-a2235d9](https://user-images.githubusercontent.com/6339511/71303134-02d2ac00-23e7-11ea-9492-65a9386fbea2.png)
Can't believe you guys didn't found this bug earlier, i triggered it several times on intro map

**Comment by Commenter25** [comment]
This has been resolved, and should be closed.

**Comment by Foohy** [comment]
Fixed in #120
