### ISSUE TITLE
:GetHTMLMaterial() can return nil on chromium (x64) branch

### ISSUE THREAD

**Issue by DBotThePony** [Foohy/jazztronauts#90]
Which can cause
![gmod_12-05-32-8d39c8d](https://user-images.githubusercontent.com/6339511/71303409-d6209380-23ea-11ea-9400-122b40279321.png)
On map scan (especially if client lag at moment of scan finish)

**Comment by roboderpy** [comment]
This is fixed in latest commit, but workshop is not updated

**Comment by Commenter25** [comment]
This has been resolved, and should be closed.

**Comment by Foohy** [comment]
Closing!
