### ISSUE TITLE
Maps from games with unsupported entities causes mass script errors and never ending waiting for players

### ISSUE THREAD

**Issue by lazyRares** [Foohy/jazztronauts#94]
when trying to launch a map from Team Fortress 2, Portal 2, Left For Dead 2. or any other valve game that isnt Jazztronauts. with the exception of Half Life 2. the game will lag SEVERELY. and the waiting for players screen will be stuck on screen.

**Comment by thekirbykid20067** [comment]
In addition to the games lazyRares mentioned, this also happens on maps from Alien Swarm & Dino D-Day.

**Comment by SageJFox** [comment]
Multiple newer map versions have been added over the years, closing issue.
