### ISSUE TITLE
Stolen Effects spawned by players still get counted.

### ISSUE THREAD

**Issue by benjaminpants** [Foohy/jazztronauts#95]
When you steal an effect spawned by a player, its counted and you get paid for it.
How recreate the bug:

Buy the GMOD Spawnmenu Upgrade
Spawn any effect
Steal it
Get paid big bucks

**Comment by Foohy** [comment]
Hmm, I'm not seeing this. What effect are you spawning, and how much is it paying out?
Currently player-spawned props give a flat reward of 2 bux, and to spawn anything it costs a flat 100, so it should still be a net loss.

**Comment by benjaminpants** [comment]
I used the Jazztronauts cat models(they are effects), I don't recall how much it paid but I know it was more then 2.

**Comment by Foohy** [comment]
Yeah, you can technically make a profit, but it'd take ages to make any meaningful profit. Even on NG++++, you'd be making 4 bucks per prop, but those upgrades are in the millions, so technically I'd say this is just by design and not actually harmful to progression.
