### ISSUE TITLE
Game crashes when trolley is summoned.

### ISSUE THREAD

**Issue by thekirbykid20067** [Foohy/jazztronauts#96]
When the trolley is summoned, Garry's Mod crashes and opens a window that says "Engine Error"
"Model models/sunabouzu/oleg_is_cool.mdl not found and models/error.mdl couldn't be loaded"

Jazztronauts was working fine before this.

**Comment by danylopez123** [comment]
That is the same problem im getting

**Comment by thekirbykid20067** [comment]
I was actually able to fix it, you just need to download "Cinema_Theatron" from the workshop.

**Comment by Commenter25** [comment]
I think this should be reopened: either it needs to say Cinema_Theatron is a required addon, or the file needs to be included in the gamemode itself. Clearly something is wrong here.

**Comment by Foohy** [comment]
Yeah, that seems like a new behavior. Before it was just an error.mdl, which while was unintentional I thought it fit with the theme of having a floating error.mdl around. Crashing isn't good, I'll fix this in a moment.

**Comment by Foohy** [comment]
This is now fixed on workshop
