### ISSUE TITLE
Prop Snatcher has the model of the HL2 pistol?

### ISSUE THREAD

**Issue by thekirbykid20067** [Foohy/jazztronauts#97]
For some reason, after joining this map (gm_exploration) and losing my prop snatcher, when i spawned it back in it had the model of the hl2 pistol. When swung, it reverted back to the stunstick, then went back to the pistol when the animation had finished. It was fixed when I picked up a magnum from the map.

https://steamcommunity.com/sharedfiles/filedetails/?id=1821648012

**Comment by SageJFox** [comment]
I've had this sort of thing happen in Sandbox, had my Physgun become an SG 552 for one life. I believe it's just a rare bug inherent to GMod.
